### ISSUE TITLE
bug: Exception in git-agent after merging repositories

### ISSUE THREAD

**Issue by ogenstad** [opsmill/infrahub#1185]
### Component

Git Integration

### Current Behavior

After merging a branch that contains an external repository that has changes there is an exception from the git-agent.

```python
Traceback (most recent call last):
  File "/Users/patrick/.virtualenvs/infrahub/bin/infrahub", line 6, in <module>
    sys.exit(app())
  File "/Users/patrick/.virtualenvs/infrahub/lib/python3.10/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/Users/patrick/.virtualenvs/infrahub/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/patrick/.virtualenvs/infrahub/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/patrick/.virtualenvs/infrahub/lib/python3.10/site-packages/typer/core.py", line 778, in main
    return _main(
  File "/Users/patrick/.virtualenvs/infrahub/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/Users/patrick/.virtualenvs/infrahub/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/patrick/.virtualenvs/infrahub/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/patrick/.virtualenvs/infrahub/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/patrick/.virtualenvs/infrahub/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/patrick/.virtualenvs/infrahub/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Users/patrick/Code/opsmill/infrahub/backend/infrahub/cli/git_agent.py", line 189, in start
    aiorun(_start(interval=interval, debug=debug, port=port))
  File "/nix/store/zmk12p33784bpcan0nfnji3agxy2z8wg-python3-3.10.12/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/zmk12p33784bpcan0nfnji3agxy2z8wg-python3-3.10.12/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/patrick/Code/opsmill/infrahub/backend/infrahub/cli/git_agent.py", line 165, in _start
    await asyncio.gather(*tasks)
  File "/Users/patrick/Code/opsmill/infrahub/backend/infrahub/cli/git_agent.py", line 135, in monitor_remote_activity
    await sync_remote_repositories(client=client)
  File "/Users/patrick/Code/opsmill/infrahub/backend/infrahub/git/actions.py", line 37, in sync_remote_repositories
    await repo.sync()
  File "/Users/patrick/Code/opsmill/infrahub/backend/infrahub/git/repository.py", line 855, in sync
    await self.import_objects_from_files(branch_name=branch_name, commit=commit_after)
  File "/Users/patrick/Code/opsmill/infrahub/backend/infrahub/git/repository.py", line 1013, in import_objects_from_files
    await self.import_all_graphql_query(branch_name=branch_name, commit=commit)
  File "/Users/patrick/Code/opsmill/infrahub/backend/infrahub/git/repository.py", line 1202, in import_all_graphql_query
    local_queries = {query.name: query for query in await self.find_graphql_queries(commit=commit)}
  File "/Users/patrick/Code/opsmill/infrahub/backend/infrahub/git/repository.py", line 1594, in find_graphql_queries
    query_files = await self.find_files(extension=["gql"], commit=commit)
  File "/Users/patrick/Code/opsmill/infrahub/backend/infrahub/git/repository.py", line 1587, in find_files
    files.extend(glob.glob(f"{branch_wt.directory}/**/*.{ext}", recursive=recursive))
AttributeError: 'NoneType' object has no attribute 'directory'
```

### Additional Information

Possibly related to the changes when we changed the worktree to be based on the branch_id instead of name.

**Comment by saltas888** [comment]
The crash reported here was `AttributeError: 'NoneType' object has no attribute 'directory'`, from `get_worktree` returning None. That path is gone, `get_worktree` now returns a `Worktree` and raises `RepositoryError` when nothing matches, and `find_files` has been reworked with proper type hints, which was the other reason this stayed open.

Closing as resolved. The separate question about local-folder repositories isn't covered here, worth its own issue if it still bites.
