### ISSUE TITLE
bug: `allocate_next_ip_prefix` generates incorrect GraphQL mutation

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#3617]
### Component

Python SDK

### Current Behavior

The method accepts a `prefix_length` argument, which is passed as the `prefix_length` field for the `IPPrefixPoolGetResourceInput` mutation. This is an incorrect field for this mutation. The mutation seems to use a `size` field which we should be using instead.

### Expected Behavior

The `allocate_next_ip_prefix` field should use the correct field for the `IPPrefixPoolGetResourceInput` mutation. The argument of the method should probably be aligned to the name of the field in the mutation.

### Steps to Reproduce

Load demo schema and data

```python
from infrahub_sdk import InfrahubClientSync

client = InfrahubClientSync.init()
internal_networks_pool = client.get(kind="CoreIPPrefixPool", name__value="Internal networks pool")

prefix = client.allocate_next_ip_prefix(resource_pool=internal_networks_pool, prefix_length=31, member_type="IpamIPAddress", identifier=f"test")
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wim/dev/infrahub/python_sdk/infrahub_sdk/client.py", line 1550, in allocate_next_ip_prefix
    response = self.execute_graphql(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/wim/dev/infrahub/python_sdk/infrahub_sdk/client.py", line 1142, in execute_graphql
    raise GraphQLError(errors=response["errors"], query=query, variables=variables)
infrahub_sdk.exceptions.GraphQLError: An error occurred while executing the GraphQL Query 
mutation AllocateIPPrefix {
    IPPrefixPoolGetResource(
        data: {
            id: "17d792b7-9c36-6254-3583-c5180ce229ee"
            identifier: "test"
            prefix_length: 31
            member_type: "IpamIPAddress"
        }
, [{'message': "Field 'prefix_length' is not defined by type 'IPPrefixPoolGetResourceInput'. Did you mean 'prefix_type'?", 'locations': [{'line': 7, 'column': 13}]}]
```

**Comment by gmazoyer** [comment]
Fixed in https://github.com/opsmill/infrahub/commit/f079426a6b370f8c66167520f70eae85dd19d633
