### ISSUE TITLE
bug: recursion error when opening a proposed change

### ISSUE THREAD

**Issue by wvandeun** [opsmill/infrahub#5292]
### Component

API Server / GraphQL

### Infrahub version

1.0.10, 1.1.0b2

### Current Behavior

CI is not starting when opening a proposed change for a branch that contains a particular schema migration.
The flow `proposed-changed-pipeline` seems to result in a RecursionError exception.

```
Encountered exception during execution: RecursionError('maximum recursion depth exceeded')
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 655, in run_context
    yield self
  File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 718, in run_flow_async
    await engine.call_flow_fn()
  File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 673, in _call_flow_fn
    result = await call_with_parameters(self.flow.fn, self.parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/message_bus/operations/requests/proposed_change.py", line 97, in pipeline
    await diff_coordinator.update_branch_diff(base_branch=destination_branch, diff_branch=source_branch)
  File "/source/backend/infrahub/core/diff/coordinator.py", line 143, in update_branch_diff
    await self.diff_repo.save(enriched_diffs=enriched_diffs)
  File "/source/backend/infrahub/database/__init__.py", line 498, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/core/diff/repository/repository.py", line 169, in save
    link_query = await EnrichedNodesLinkQuery.init(db=self.db, enriched_diffs=enriched_diffs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/core/query/__init__.py", line 401, in init
    await query.query_init(db=db, **kwargs)
  File "/source/backend/infrahub/core/diff/query/save.py", line 334, in query_init
    parent_links_list.extend(self._build_node_parent_links(enriched_node=node, root_uuid=diff_root.uuid))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/core/diff/query/save.py", line 368, in _build_node_parent_links
    parent_links.extend(self._build_node_parent_links(enriched_node=child_node, root_uuid=root_uuid))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/core/diff/query/save.py", line 368, in _build_node_parent_links
    parent_links.extend(self._build_node_parent_links(enriched_node=child_node, root_uuid=root_uuid))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/core/diff/query/save.py", line 368, in _build_node_parent_links
    parent_links.extend(self._build_node_parent_links(enriched_node=child_node, root_uuid=root_uuid))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 968 more times]
RecursionError: maximum recursion depth exceeded
```

When you do try to merge the proposed change after we run into the RecursionError exception, the merge failed and we got the following log message

```
Encountered exception during execution: MergeFailedError("Failed to merge branch 'test'")
Traceback (most recent call last):
  File "/source/backend/infrahub/core/branch/tasks.py", line 186, in merge_branch
    await merger.merge()
  File "/source/backend/infrahub/core/merge.py", line 177, in merge
    enriched_diff = await self.diff_coordinator.update_branch_diff(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/core/diff/coordinator.py", line 143, in update_branch_diff
    await self.diff_repo.save(enriched_diffs=enriched_diffs)
  File "/source/backend/infrahub/database/__init__.py", line 498, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/core/diff/repository/repository.py", line 169, in save
    link_query = await EnrichedNodesLinkQuery.init(db=self.db, enriched_diffs=enriched_diffs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/core/query/__init__.py", line 401, in init
    await query.query_init(db=db, **kwargs)
  File "/source/backend/infrahub/core/diff/query/save.py", line 334, in query_init
    parent_links_list.extend(self._build_node_parent_links(enriched_node=node, root_uuid=diff_root.uuid))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/core/diff/query/save.py", line 368, in _build_node_parent_links
    parent_links.extend(self._build_node_parent_links(enriched_node=child_node, root_uuid=root_uuid))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/core/diff/query/save.py", line 368, in _build_node_parent_links
    parent_links.extend(self._build_node_parent_links(enriched_node=child_node, root_uuid=root_uuid))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/core/diff/query/save.py", line 368, in _build_node_parent_links
    parent_links.extend(self._build_node_parent_links(enriched_node=child_node, root_uuid=root_uuid))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 965 more times]
RecursionError: maximum recursion depth exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 655, in run_context
    yield self
  File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 718, in run_flow_async
    await engine.call_flow_fn()
  File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 673, in _call_flow_fn
    result = await call_with_parameters(self.flow.fn, self.parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/proposed_change/tasks.py", line 134, in merge_proposed_change
    await merge_branch(branch=source_branch.name)
  File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 720, in run_flow_async
    return engine.state if return_type == "state" else engine.result()
                                                       ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 255, in result
    raise self._raised
  File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 655, in run_context
    yield self
  File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 718, in run_flow_async
    await engine.call_flow_fn()
  File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 673, in _call_flow_fn
    result = await call_with_parameters(self.flow.fn, self.parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/source/backend/infrahub/core/branch/tasks.py", line 189, in merge_branch
    raise MergeFailedError(branch_name=branch) from exc
infrahub.exceptions.MergeFailedError: Failed to merge branch 'test'
```

### Expected Behavior

CI tasks start normally

### Steps to Reproduce

- start instance of Infrahub
- load the base schema from the schema-library `infrahubctl schema load base/`
- create a bit of data using the following script
```python
from infrahub_sdk import InfrahubClientSync, Config

client = InfrahubClientSync()

mf = client.create("OrganizationManufacturer", name="Cisco")
mf.save()

pf = client.create("DcimPlatform", name="cisco_ios", manufacturer=mf)
pf.save()

dt = client.create("DcimDeviceType", name="test", manufacturer=mf, platform=pf)
dt.save()
```
- create a branch `test` `infrahubctl branch create test`
- load the location_minimal schema from the schema-library into the test branch `infrahubctl schema load extensions/location_minimal/ --branch test
- create some data in the branch
```python
from infrahub_sdk import InfrahubClientSync, Config

client = InfrahubClientSync(config=Config(default_branch="test"))

country = client.create("LocationCountry", name="Netherlands", shortname="NL")
country.save()

metro = client.create("LocationMetro", name="Gelderland", shortname="GLD", parent=country)
metro.save()

site = client.create("LocationSite", name="Home", shortname="hm", parent=metro)
site.save()
```
- open a proposed change for the branch test
- notice that there is no tasks starting
- open prefect and navigate to runs
- you should see a `proposed-changed-pipeline` flow that failed, open it to see the RecursionError exception
- try to merge the proposed change
- it will fail, navigate to tasks, the merge task will contain the error message

### Additional Information

- in the schema diff tab of the proposed change there is a removal reported, if you click on it to filter the diff then it says there is no matches found. This is weird as we didn't remove anything from the schema.
- if you navigate to the bottom of the schema diff, you will see a change reported on the Provider schema node. On it you will see a removal of the tags relationship. This is weird, as we didn't remove the tags relationship. Also the tags relationships still seems to exist

- when we try to merge this branch, without a proposed change, for example through the CLI, you sometimes also run into this error message
```
{
  "name": "ApolloError",
  "graphQLErrors": [
    {
      "message": "Node (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/min_count',\nNode (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/min_count',\nNode (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/cardinality',\nNode (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/cardinality',\nNode (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/max_count',\nNode (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/max_count'",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "BranchMerge"
      ]
    }
  ],
  "protocolErrors": [],
  "clientErrors": [],
  "networkError": null,
  "message": "Node (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/min_count',\nNode (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/min_count',\nNode (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/cardinality',\nNode (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/cardinality',\nNode (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/max_count',\nNode (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/max_count'",
  "cause": {
    "message": "Node (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/min_count',\nNode (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/min_count',\nNode (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/cardinality',\nNode (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/cardinality',\nNode (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/max_count',\nNode (SchemaRelationship: 1812fd22-df7e-9835-3c3e-c51e9546a18b) is not compatible with the constraint 'relationship.count.update' at 'schema/SchemaRelationship/node/max_count'",
    "locations": [
      {
        "line": 2,
        "column": 3
      }
    ],
    "path": [
      "BranchMerge"
    ]
  }
}

```
when looking up the UUI of the relationship in question, it seems to be the same tags relationship on the Provider schemanode that reports wrongly in the diff.

**Comment by ajtmccarty** [comment]
- the root cause of the recursion error is a problem in how we calculate the hierarchy of a given node. it will be fixed in #5420 
- the other issues that you saw that were related to the `tags` relationship on the `OrganizationProvider` schema is unrelated to the diff. In fact, the diff helped correctly identify an issue with how we load relationships in schema extensions. I've made a Jira issue for it (IFC-1090)
